name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.17.x

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Code coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
